public without sharing class RepositoryMain implements InterfaceRepositoryMain{

    public void updateCustomers(List<Customer> updateCustomers){
        update updateCustomers;
    }

    public void updateCustomersSupports(List<Customer_Support__c> updateCustomersSupports){
        update updateCustomersSupports;
    }

    public void insertCustomerSupport(Customer_Support__c insertCustomerSupport){
        insert insertCustomerSupport;
    }

}